### ISSUE TITLE
how compile it from source code?

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#64]
would you please tell us how compile from source code. I tryed vs2017, vscode with dotnet

E:\Dev\sharp\neolua\NeoLua\NeoLua.csproj(95,3): error MSB4019: Imported project 'C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Portable\v4.5' not found \Microsoft.Portable.CSharp.targets". Please confirm <Import>
The path in the declaration is correct and the file exists on the disk.
E:\Dev\sharp\neolua\NeoLua.NuGet\Package.targets(9,2): error MSB4019: Imported project "E:\Dev\sharp\neolua\NeoLua.NuGet\package.apikey.targets" was not found . Please make sure the path in the <Import> statement is correct and exists on the disk
The document. [E:\Dev\sharp\neolua\NeoLua.NuGet\NeoLua.NuGet.csproj]
E:\Dev\sharp\neolua\NeoLua\NeoLua.csproj(95,3): error MSB4019: Imported project 'C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Portable\v4.5' not found \Microsoft.Portable.CSharp.targets". Please confirm <Import>
The path in the declaration is correct and the file exists on the disk.
E:\Dev\sharp\neolua\NeoLua\NeoLua.csproj(95,3): error MSB4019: Imported project 'C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Portable\v4.5' not found \Microsoft.Portable.CSharp.targets". Please confirm <Import>
The path in the declaration is correct and the file exists on the disk.
E:\Dev\sharp\neolua\NeoLua\NeoLua.csproj(95,3): error MSB4019: Imported project 'C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Portable\v4.5' not found \Microsoft.Portable.CSharp.targets". Please confirm <Import>
The path in the declaration is correct and the file exists on the disk.
E:\Dev\sharp\neolua\NeoLua\NeoLua.csproj(95,3): error MSB4019: Imported project 'C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Portable\v4.5' not found \Microsoft.Portable.CSharp.targets". Please confirm <Import>
The path in the declaration is correct and the file exists on the disk.

**Comment by FashGek** [comment]
I should try myself

**Comment by FashGek** [comment]
my dotnet sdk dosenot have C:\Program Files\dotnet\sdk\2.0.2\Microsoft\Portable\ this directory. my dotnet version 2.0.2

**Comment by FashGek** [comment]
after I install .NET Core 2.1.101 SDK, sill cannto no portable directory

**Comment by FashGek** [comment]
I copy the portabel directory form another place, it dose not say that kind of eroor, but it cannot compatable with targetframwork with netcoreapp2.0

**Comment by FashGek** [comment]
LuaChunk.cs(97,28): error CS0656: the compiler ask  member   below ,“Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create” [E:\Dev\sharp\testneolua\NeoLua\NeoLua.csproj]


my csproj is below
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.CSharp" Version="1.0.0" />
  </ItemGroup>
</Project>

**Comment by neolithos** [comment]
I had no issues to compile the project, I just install the .net profile of vs2017?

* .NET Core-Runtime
* .NET Framework 4.7 SDK
* .NET Framework 4.7 Targets
* .NET Native
* C# and Visual Basic Roslyn Compiler
* MSBuild
* C# and Visual Basic

**Comment by FashGek** [comment]
thank you i will check my instal list , maybe i donot have msbuild
